var webpack = require("webpack");
var HtmlWebpackPlugin = require("html-webpack-plugin");
module.exports={
    entry:__dirname+"/src/main.js",
    output:{
        path:__dirname+"/dist",
        filename:"[name].js"
    },			
    module:{
        rules:[
        {
            test:/\.js$/,
            use:["babel-loader"]
        },
        {
            test:/\.vue$/,
            include:/src/,
            use:["vue-loader"]
        },
        {
            test:/\.css$/,
            use:["style-loader","css-loader"]
        },
        {
            test:/\.html$/,
            loader:"html-loader"
        },
        {
            test:/\.png|.jpg$/,
            loader:"url-loader"
        }]
    },
    devServer:{
        port:8888,
        host: 'localhost',
        hot:true,
    setup(app){
        app.get("/some/path",function(req,res){
                res.json([
                    {
                      "tex":"音乐",
                      "color":"pink",
                      "src":"yinyue"
                    },
                    {
                      "tex":"历史",
                      "color":"skyblue",
                      "src":"lishi"
                    },
                    {
                      "tex":"情感生活",
                      "color":"red",
                      "src":"ganqing"
                    },
                    {
                      "tex":"人文",
                      "color":"skyblue",
                      "src":"renwen"
                    },
                    {
                      "tex":"付费精品",
                      "color":"pink",
                      "src":"fufei"
                    },
                    {
                      "tex":"脱口秀",
                      "color":"orange",
                      "src":"tuo"
                    },
                    {
                      "tex":"娱乐",
                      "color":"red",
                      "src":"yue"
                    },
                    {
                      "tex":"英语",
                      "color":"pink",
                      "src":"english"
                    },
                    {
                      "tex":"教育培训",
                      "color":"yellow",
                      "src":"xun"
                    },
                        {
                      "tex":"音乐",
                      "color":"pink",
                      "src":"music1"
                    },
                    {
                      "tex":"历史",
                      "color":"skyblue",
                      "src":"lishi2"
                    },
                    {
                      "tex":"情感生活",
                      "src":"h"
                    },
                    {
                      "tex":"人文",
                      "src":"ren"
                    },
                    {
                      "tex":"付费精品",
                     "src":"jiig"
                    },
                    {
                      "tex":"脱口秀",
                      "src":"dfg"
                    },
                    {
                      "tex":"娱乐",
                      "src":"asd"
                    }
                ])
            })
        }
        
    },
    resolve:{
        alias:{
            "vue":"vue/dist/vue.js"
        }
    },
    plugins:[
        // new webpack.optimize.UglifyJsPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new HtmlWebpackPlugin({
            template:"./index.html"
        })
    ]
}